In [1]:
import pandas  as pd
import numpy as np

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
import seaborn as sns

In [3]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [5]:
df.dropna(inplace=True)

In [6]:
df.head

<bound method NDFrame.head of       Age  Pclass  SibSp  Parch  Survived
0    22.0       3      1      0         0
1    38.0       1      1      0         1
2    26.0       3      0      0         1
3    35.0       1      1      0         1
4    35.0       3      0      0         0
..    ...     ...    ...    ...       ...
885  39.0       3      0      5         0
886  27.0       2      0      0         0
887  19.0       1      0      0         1
889  26.0       1      0      0         1
890  32.0       3      0      0         0

[714 rows x 5 columns]>

In [7]:
x = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [8]:
x.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [9]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [15]:
np.mean(
    cross_val_score(
        LogisticRegression(),
        x,
        y,
        scoring='accuracy',
        cv=20
    )
)

0.6933333333333332

In [16]:
x['family_size'] = x['SibSp'] + x['Parch'] + 1

In [17]:
def myFun(num):
    if(num == 1):
        return 0
    elif(num > 1 and num <= 4):
        return 1
    else:
        return 2

In [18]:
x['family_type'] = x['family_size'].apply(myFun)

In [19]:
x.drop(['SibSp','Parch','family_size'],axis=1,inplace=True)

In [20]:
x.head()

    Age  Pclass  family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [21]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

0.7003174603174602

In [22]:
## Feature Splitting

In [23]:
df = pd.read_csv('train.csv')