In [2]:
import pandas  as pd
import numpy as np

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
import seaborn as sns

In [4]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [5]:
df.dropna(inplace=True)

In [6]:
df.head

<bound method NDFrame.head of       Age  Pclass  SibSp  Parch  Survived
0    22.0       3      1      0         0
1    38.0       1      1      0         1
2    26.0       3      0      0         1
3    35.0       1      1      0         1
4    35.0       3      0      0         0
..    ...     ...    ...    ...       ...
885  39.0       3      0      5         0
886  27.0       2      0      0         0
887  19.0       1      0      0         1
889  26.0       1      0      0         1
890  32.0       3      0      0         0

[714 rows x 5 columns]>

In [7]:
x = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [8]:
x.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [9]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [10]:
np.mean(
    cross_val_score(
        LogisticRegression(),
        x,
        y,
        scoring='accuracy',
        cv=20
    )
)

0.6933333333333332

In [11]:
x['family_size'] = x['SibSp'] + x['Parch'] + 1

In [12]:
def myFun(num):
    if(num == 1):
        return 0
    elif(num > 1 and num <= 4):
        return 1
    else:
        return 2

In [13]:
x['family_type'] = x['family_size'].apply(myFun)

In [14]:
x.drop(['SibSp','Parch','family_size'],axis=1,inplace=True)

In [15]:
x.head()

    Age  Pclass  family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [16]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

0.7003174603174602

In [17]:
## Feature Splitting

In [18]:
df = pd.read_csv('train.csv')

In [19]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [21]:
df['Title'] = df['Name'].str.split(',').str[1].str.split('.', expand=True)[0]

In [23]:
df['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[1].str.split('.',expand=True)[0]

0                                 Owen Harris
1       John Bradley (Florence Briggs Thayer)
2                                       Laina
3               Jacques Heath (Lily May Peel)
4                               William Henry
                        ...
886                                    Juozas
887                            Margaret Edith
888                  Catherine Helen "Carrie"
889                               Karl Howell
890                                   Patrick
Name: 0, Length: 891, dtype: object