In [57]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [58]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
data = requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers = headers)

In [59]:
soup = BeautifulSoup(data.text, 'lxml')

In [12]:
soup.find_all('h1')[0].text

'\n\t\t\t\t\tTop Companies in\n\t\t\t\t \n\t\t\t\t\tINDIA\n\t\t\t\t\t'

In [60]:
#soup.find_all('h2')

In [24]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [30]:
for i in soup.find_all("div", class_="rating_text"):
    print(i.text.strip())

3.3
3.7
3.6
3.7
3.6
3.8
3.5
3.4
3.9
3.4
3.6
3.9
4.4
3.6
3.6
3.9
3.9
4.6
3.6
3.9

In [48]:
companyName=[]
rating=[]
review=[]
for i in soup.find_all("div",class_='companyCardWrapper__primaryInformation'):
    companyName.append(i.find("h2",class_='companyCardWrapper__companyName').text.strip())
    rating.append(i.find("div", class_="rating_text rating_text--md").text.strip())
    review.append(i.find("span",class_="companyCardWrapper__companyRatingCount").text.strip())

In [52]:
d={'name':companyName, 'rating':rating, 'review':review}
df = pd.DataFrame(d)

                      name rating   review
0                      TCS    3.3   (1.2L)
1                Accenture    3.7  (74.3k)
2                    Wipro    3.6  (65.7k)
3                Cognizant    3.7    (62k)
4                Capgemini    3.6    (54k)
5                HDFC Bank    3.8  (53.1k)
6                  Infosys    3.5  (49.3k)
7                  HCLTech    3.4  (46.5k)
8               ICICI Bank    3.9  (46.3k)
9            Tech Mahindra    3.4  (43.7k)
10                 Genpact    3.6  (42.8k)
11                      TP    3.9  (39.1k)
12                     Jio    4.4  (33.8k)
13               Axis Bank    3.6  (33.7k)
14  Concentrix Corporation    3.6  (32.6k)
15                  Amazon    3.9  (31.8k)
16         Reliance Retail    3.9  (27.6k)
17              iEnergizer    4.6  (27.3k)
18             LTIMindtree    3.6  (26.7k)
19                     IBM    3.9    (26k)

In [62]:
companyName=[]
rating=[]
review=[]
for i in range(1,11):
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    data = requests.get(f'https://www.ambitionbox.com/list-of-companies?page={i}',headers = headers,timeout=10)
    soup = BeautifulSoup(data.text, 'lxml')
    
    for i in soup.find_all("div",class_='companyCardWrapper__primaryInformation'):
        companyName.append(i.find("h2",class_='companyCardWrapper__companyName').text.strip())
        rating.append(i.find("div", class_="rating_text rating_text--md").text.strip())
        review.append(i.find("span",class_="companyCardWrapper__companyRatingCount").text.strip())
    d={'name':companyName, 'rating':rating, 'review':review}
    df = pd.DataFrame(d)

In [63]:
df

                                name rating   review
0                                TCS    3.3   (1.2L)
1                          Accenture    3.7  (74.3k)
2                              Wipro    3.6  (65.7k)
3                          Cognizant    3.7    (62k)
4                          Capgemini    3.6    (54k)
..                               ...    ...      ...
195              Pidilite Industries    4.2     (4k)
196                Grasim Industries    4.0     (4k)
197  Aditya Birla Sun Life Insurance    4.0   (3.9k)
198                        Oyo Rooms    3.0   (3.9k)
199                          Kyndryl    4.0   (3.9k)

[200 rows x 3 columns]